export const IS_LOADED = 'IS_LOADED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PLAYER_COMPS = 'GET_PLAYER_COMPS';
export const GET_PLAYER_OFFERS = 'GET_PLAYER_OFFERS';
export const SUCCUSS_TRANSITION = 'SUCCUSS_TRANSITION';
export const FAILED_TRANSITION = 'FAILED_TRANSITION';

export const GET_ALL_COMPETITIONS = 'GET_ALL_COMPETITIONS';
export const GET_TOP_COMPETITIONS = 'GET_TOP_COMPETITIONS';
export const GET_SINGLE_COMPETITION = 'GET_SINGLE_COMPETITION';
export const CHECK_IF_USER_JOINED_COMPETITION = 'CHECK_IF_USER_JOINED_COMPETITION';
export const JOIN_COMPETITION = 'JOIN_COMPETITION';

export const GET_ALL_GAMES = 'GET_ALL_GAMES';
export const GET_SINGLE_GAME = 'GET_SINGLE_GAME';

export const GET_ALL_OFFERS = 'GET_ALL_OFFERS';
export const GET_SINGLE_OFFER = 'GET_SINGLE_OFFER';

export const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const GET_SINGLE_GROUP = 'GET_SINGLE_GROUP';
export const GET_GROUP_POSTS = 'GET_GROUP_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const CHECK_IF_USER_JOINED_GROUP = 'CHECK_IF_USER_JOINED_GROUP';
export const JOIN_GROUP = 'JOIN_GROUP';
export const GET_GROUP_MEMBERS = 'GET_GROUP_MEMBERS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_MSG = 'CLEAR_MSG';


export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU';
export const LOADING = 'LOADING';
export const END_LOADING = 'END_LOADING';

